from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "web" / "index.html"
STYLE = ROOT / "web" / "style.css"
APP = ROOT / "web" / "app.js"
DEFAULT_OUTPUT = ROOT / "standalone" / "sayelf-cq-municipal-cad-qto.html"
API_BASE = "http://127.0.0.1:8765"


def build(output: Path) -> Path:
    html = INDEX.read_text(encoding="utf-8")
    css = STYLE.read_text(encoding="utf-8")
    app = APP.read_text(encoding="utf-8")
    stylesheet_tag = '<link rel="stylesheet" href="/style.css">'
    script_tag = '<script src="/app.js"></script>'
    if html.count(stylesheet_tag) != 1 or html.count(script_tag) != 1:
        raise RuntimeError("web/index.html 的 CSS/JS 入口与构建器预期不一致")
    inline_css = f"<style data-generated-from=\"web/style.css\">\n{css}\n</style>"
    api_config = f'<script>window.CAD_QTO_API_BASE = "{API_BASE}";</script>'
    inline_app = f"<script data-generated-from=\"web/app.js\">\n{app}\n</script>"
    standalone = html.replace(stylesheet_tag, inline_css).replace(script_tag, api_config + "\n" + inline_app)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "<!-- Generated by scripts/build_standalone_html.py; edit web/ sources instead. -->\n" + standalone,
        encoding="utf-8",
        newline="\n",
    )
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the single-file local CAD QTO HTML deliverable.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output HTML path")
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    print(build(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
